import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // One row per sync key. The key is a 128-bit random capability generated by the
  // first device; anyone holding it can read/write that state — same trust model as
  // a private pastebin link. No accounts.
  states: defineTable({
    key: v.string(),
    state: v.any(),
    updated: v.number(),
  }).index("by_key", ["key"]),
  keyOwners: defineTable({
    subject: v.string(),
    key: v.string(),
    createdAt: v.number(),
  }).index("by_subject", ["subject"]),
});
