import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // One row per sync key. The key is a 128-bit random capability generated by the
  // first device; anyone holding it can read/write that state — same trust model as
  // a private pastebin link. No accounts.
  // A revoked row is a tombstone, not a deletion: push() creates a row for any
  // unseen key, so deleting a rotated key would let a stale device silently
  // resurrect it as an empty state and believe it was still syncing. The tombstone
  // deliberately records no pointer to the replacement — an old key must never be
  // a route to the new one, or rotation would be decorative.
  states: defineTable({
    key: v.string(),
    state: v.any(),
    updated: v.number(),
    revoked: v.optional(v.boolean()),
    revokedAt: v.optional(v.number()),
  }).index("by_key", ["key"]),
  keyOwners: defineTable({
    subject: v.string(),
    key: v.string(),
    createdAt: v.number(),
    rotatedAt: v.optional(v.number()),
  }).index("by_subject", ["subject"])
    // Rotation has to re-point owners by the key being retired, including on the
    // capability path where no subject is presented.
    .index("by_key", ["key"]),
});
